package newsApi

type Category string

const (
	CAT_BUSINESS      Category = "business"
	CAT_ENTERTAINMENT Category = "entertainment"
	CAT_GENERAL       Category = "general"
	CAT_HEALTH        Category = "health"
	CAT_SCIENCE       Category = "science"
	CAT_SPORTS        Category = "sports"
	CAT_TECHNOLOGY    Category = "technology"
)

type Language string

const (
	LANG_ARABIC        Language = "ar"
	LANG_AR            Language = "ar"
	LANG_GERMAN        Language = "de"
	LANG_DE            Language = "de"
	LANG_ENGLISH       Language = "en"
	LANG_EN            Language = "en"
	LANG_SPANISH       Language = "es"
	LANG_ES            Language = "es"
	LANG_FRENCH        Language = "fr"
	LANG_FR            Language = "fr"
	LANG_HEBREW        Language = "he"
	LANG_HE            Language = "he"
	LANG_ITALIAN       Language = "it"
	LANG_IT            Language = "it"
	LANG_DUTCH         Language = "nl"
	LANG_NL            Language = "nl"
	LANG_NORWEGIAN     Language = "no"
	LANG_NO            Language = "no"
	LANG_PORTUGUESE    Language = "pt"
	LANG_PT            Language = "pt"
	LANG_RUSSIAN       Language = "ru"
	LANG_RU            Language = "ru"
	LANG_NORTHERN_SAMI Language = "se"
	LANG_SE            Language = "se"
	LANG_UD            Language = "ud" // TODO: which country/full-form
	LANG_CHINESE       Language = "zh"
	LANG_ZH            Language = "zh"
)

type Country string

const (
	CNTRY_UAE                      Country = "ae"
	CNTRY_AE                       Country = "ae"
	CNTRY_ARGENTINA                Country = "ar"
	CNTRY_AR                       Country = "ar"
	CNTRY_AUSTRIA                  Country = "at"
	CNTRY_AT                       Country = "at"
	CNTRY_AUSTRALIA                Country = "au"
	CNTRY_AU                       Country = "au"
	CNTRY_BELGIUM                  Country = "be"
	CNTRY_BE                       Country = "be"
	CNTRY_BULGARIA                 Country = "bg"
	CNTRY_BG                       Country = "bg"
	CNTRY_BRAZIL                   Country = "br"
	CNTRY_BR                       Country = "br"
	CNTRY_CANADA                   Country = "ca"
	CNTRY_CA                       Country = "ca"
	CNTRY_SWITZERLAND              Country = "ch"
	CNTRY_CH                       Country = "ch"
	CNTRY_CHINA                    Country = "cn"
	CNTRY_CN                       Country = "cn"
	CNTRY_COLOMBIA                 Country = "co"
	CNTRY_CO                       Country = "co"
	CNTRY_CUBA                     Country = "cu"
	CNTRY_CU                       Country = "cu"
	CNTRY_CZECH_REPUBLIC           Country = "cz"
	CNTRY_CZ                       Country = "cz"
	CNTRY_GERMANY                  Country = "de"
	CNTRY_DE                       Country = "de"
	CNTRY_EGYPT                    Country = "eg"
	CNTRY_EG                       Country = "eg"
	CNTRY_FRANCE                   Country = "fr"
	CNTRY_FR                       Country = "fr"
	CNTRY_UNITED_KINGDOM           Country = "gb"
	CNTRY_GB                       Country = "gb"
	CNTRY_GREECE                   Country = "gr"
	CNTRY_GR                       Country = "gr"
	CNTRY_HONG_KONG                Country = "hk"
	CNTRY_HK                       Country = "hk"
	CNTRY_HUNGARY                  Country = "hu"
	CNTRY_HU                       Country = "hu"
	CNTRY_INDONESIA                Country = "id"
	CNTRY_ID                       Country = "id"
	CNTRY_IRELAND                  Country = "ie"
	CNTRY_IE                       Country = "ie"
	CNTRY_ISRAEL                   Country = "il"
	CNTRY_IL                       Country = "il"
	CNTRY_INDIA                    Country = "in"
	CNTRY_IN                       Country = "in"
	CNTRY_ITALY                    Country = "it"
	CNTRY_IT                       Country = "it"
	CNTRY_JAPAN                    Country = "jp"
	CNTRY_JP                       Country = "jp"
	CNTRY_SOUTH_KOREA              Country = "kr"
	CNTRY_KR                       Country = "kr"
	CNTRY_LITHUANIA                Country = "lt"
	CNTRY_LT                       Country = "lt"
	CNTRY_LATVIA                   Country = "lv"
	CNTRY_LV                       Country = "lv"
	CNTRY_MOROCCO                  Country = "ma"
	CNTRY_MA                       Country = "ma"
	CNTRY_MEXICO                   Country = "mx"
	CNTRY_MX                       Country = "mx"
	CNTRY_MALAYSIA                 Country = "my"
	CNTRY_MY                       Country = "my"
	CNTRY_NIGERIA                  Country = "ng"
	CNTRY_NG                       Country = "ng"
	CNTRY_NETHERLANDS              Country = "nl"
	CNTRY_NL                       Country = "nl"
	CNTRY_NORWAY                   Country = "no"
	CNTRY_NO                       Country = "no"
	CNTRY_NEW_ZEALAND              Country = "nz"
	CNTRY_NZ                       Country = "nz"
	CNTRY_PHILIPPINES              Country = "ph"
	CNTRY_PH                       Country = "ph"
	CNTRY_POLAND                   Country = "pl"
	CNTRY_PL                       Country = "pl"
	CNTRY_PORTUGAL                 Country = "pt"
	CNTRY_PT                       Country = "pt"
	CNTRY_ROMANIA                  Country = "ro"
	CNTRY_RO                       Country = "ro"
	CNTRY_SERBIA                   Country = "rs"
	CNTRY_RS                       Country = "rs"
	CNTRY_RUSSIAN_FEDERATION       Country = "ru"
	CNTRY_RU                       Country = "ru"
	CNTRY_SAUDI_ARABIA             Country = "sa"
	CNTRY_SA                       Country = "sa"
	CNTRY_SWEDEN                   Country = "se"
	CNTRY_SE                       Country = "se"
	CNTRY_SINGAPORE                Country = "sg"
	CNTRY_SG                       Country = "sg"
	CNTRY_SLOVENIA                 Country = "si"
	CNTRY_SI                       Country = "si"
	CNTRY_SLOVAKIA                 Country = "sk"
	CNTRY_SK                       Country = "sk"
	CNTRY_THAILAND                 Country = "th"
	CNTRY_TH                       Country = "th"
	CNTRY_TURKEY                   Country = "tr"
	CNTRY_TR                       Country = "tr"
	CNTRY_TAIWAN                   Country = "tw"
	CNTRY_TW                       Country = "tw"
	CNTRY_UKRAINE                  Country = "ua"
	CNTRY_UA                       Country = "ua"
	CNTRY_UNITED_STATES_OF_AMERICA Country = "us"
	CNTRY_US                       Country = "us"
	CNTRY_VENEZUELA                Country = "ve"
	CNTRY_VE                       Country = "ve"
	CNTRY_SOUTH_AFRICA             Country = "za"
	CNTRY_ZA                       Country = "za"
)

type SortBy string

const (
	SORT_BY_RELEVANCY    SortBy = "relevancy"
	SORT_BY_POPULARITY   SortBy = "popularity"
	SORT_BY_PUBLISHED_AT SortBy = "publishedAt"
)
